#!/bin/bash
#
#	Ciboulette una red social 100% libre, descentralizada y entre pares
#	version 0.3
#	AGPLv3+ © bazza
#

export NOMBRE="ciboulette"
export CARPETA=~/.${NOMBRE}/
export BLOG="${CARPETA}blog"
export COMPARTIR="${CARPETA}compartir"
export NOVEDADES="${CARPETA}novedades"

#---------------------- funciones graficas -----------------
function opciones {
	while getopts t:m: OPCION; do
	        case $OPCION in
	                t) TITULO=${OPTARG}
	                ;;
	                m) MENSAJE=${OPTARG}
	                ;;
	        esac
	done
	# parametros
	N=0
	for T in $(cat /dev/stdin); do
		T=$(echo $T | sed 's/_/\ /g')
		C="$C $N \"$T\""
		N=$(($N+1))
	done
	# genera el menu
	eval "zenity --title \"$TITULO\" --window-icon /usr/share/pixmaps/$NOMBRE.png --text \"$MENSAJE\" --list --height=250 --column \"\" --column \"\" --hide-column 1  --hide-header $C"
}

function error {
	zenity --error --text="$*"
}
function alerta {
	zenity --warning --text="$(cat /dev/stdin)"
}
function clave {
	zenity --title "Clave" --text "Introducir la clave" --entry --entry-text="$*"
}
function url {
	zenity --title "URL" --text "Dirección" --entry --entry-text="$*"
}
function titulo {
	zenity --title "Titulo" --text "¿Sobre que vas a hablar?" --entry --entry-text="$*"
}
function archivo {
	zenity --title "Elije el archivo" --file-selection
}
function archivos {
	echo -e "$(zenity --title "Archivos" --text="Elije los archivos" --file-selection --multiple --separator="\n" \
	|| error "si necesita un archivo" && exit)"
}
function mensaje {
	zenity --title "Mensaje" --text="Escribe el mensaje" --width=450 --height=350 --text-info --editable
}
function mostrar {
	# mensaje de entrada
	MENSAJE=`cat /dev/stdin`
	if [ "$(echo "$MENSAJE" | wc -l )" == "1" ]; then
		zenity --title "Mensaje decifrado" --width=450 --text="$*" --entry --entry-text="$MENSAJE"
	else
		echo "$MENSAJE" | zenity --title "Mensaje decifrado" --text="$*" --width=450 --height=350 --text-info
	fi
	echo "$MENSAJE" | xsel -i
}
function progreso {
	pid=`mktemp`
	zenity --progress --pulsate --auto-close --title "Espere por favor..." --text="$*" & echo $! > $pid
	cat /dev/stdin
	kill `cat $pid`
}
function blogear {
	# nanoblogger construye el blog
	nb -b $BLOG --template-dir $BLOG/templates update all
}

function servidor_inicio {
	# inicia el servidor
	rm -f /tmp/$NOMBRE.pid
	# Si corremos arch
	[ "$(uname -r | grep ARCH)" ] && darkhttpd $BLOG --port 4232 --pidfile /tmp/$NOMBRE.pid || \
	/usr/sbin/mini-httpd -i /tmp/$NOMBRE.pid -p 4232 -d "$BLOG" -T "UTF8" -c "cgi-bin/*"
	[ "$(uname -r | grep ARCH)" ] && darkhttpd "$NOVEDADES" --port 4233 --pidfile /tmp/${NOMBRE}N.pid || \
	/usr/sbin/mini-httpd -i /tmp/${NOMBRE}N.pid -p 4233 -d "$NOVEDADES" -T "UTF8" -c "cgi-bin/*"
}
function servidor_matar {
	# matar el servidor
	[ -f /tmp/$NOMBRE.pid ] && kill "$(cat /tmp/$NOMBRE.pid)" 2> /dev/null
}

function nodo_agregar {
	URL=`cat /dev/stdin`
	torify rawdog -d $NOVEDADES -a "$URL" 2> /dev/null
}
function nodo_borrar {
	URL=`cat /dev/stdin`
	torify rawdog -d $NOVEDADES -r "$URL" 2> /dev/null
}
function nodos_lista {
	torify rawdog -d $NOVEDADES -l 2> /dev/null
}
function nodos_actualizar {
	N=$(torify rawdog -d $NOVEDADES -wu | cut -d " " -f1) 2> /dev/null
	export DISPLAY=:0
	[ "$N" -gt 0 ] && notify-send -t -1 "Ciboulette" "<a href=\"http://localhost:4232/novedades\">$ID</a>$N mensajes</a>" -i "${CARPETA}imagen.png"
}


while getopts a:b:n:skdlhiuw OPCION; do
	case $OPCION in
               a)
			echo "Publicando articulo"
			# se necesita un metodo para crear un articulo
			nb -b $BLOG --template-dir $BLOG/templates add entry
			blogear
			exit
                ;;
                w) blogear; exit
                ;;
                n) echo ${OPTARG} | nodo_agregar; exit
                ;;
                b) echo ${OPTARG} | nodo_borrar; exit
                ;;
                l) nodos_lista; exit
                ;;
                d) nodos_actualizar; exit
                ;;
                s) servidor_matar
		   servidor_inicio
		 exit
                ;;
                k)
			servidor_matar; exit
                ;;
	u)
		NOMBRE=`basename $0`
        	AUTOR="b4zz4"
		REPO="Ciboulette"
		ZIP="master"
		cd /tmp
		# unificar estas dos lineas
		wget https://github.com/$AUTOR/$REPO/archive/$ZIP.zip -O master.zip
		rm -r $REPO-$ZIP/
		unzip master.zip
		cd $REPO-$ZIP/
		chmod +x $NOMBRE
		./$NOMBRE -i && echo "actualizado"
		exit
	;;
	h)
		echo "$(basename $0) $(cat ${CARPETA}hostname)"
		echo
		echo "  -h | esta ayuda"
		echo "  -i | instalación"
		echo "  -w | actualizar tu ciboulette"
		echo "  -s | iniciar el servidor"
		echo "  -k | matar el servidor"
		echo "  -a [titulo texto] | agregar articulo"
		echo "  -n [url del nodo] | agregar nodo"
		echo "  -d | actualizar noticias"
		echo "  -b [url del nodo] | borrar nodo"
		echo "  -l | lisa de nodos "
		echo "  -u Actualizar la aplicación"
		exit
	;;
	i)
		NOMBRE=`basename $0`
		echo -e "[Desktop Entry]\nName=$NOMBRE\nDescription=Red Social 100% Libre\nIcon=help-faq\nType=Application\nExec=$NOMBRE\nCategories=GTK;Utility;" > /tmp/$NOMBRE.desktop
		# dependencias
		TMP=$(mktemp)

		# - instala dependencias
		# - crea servicio oculto
		# - genera las carpetas
		# - copia las configuraciones de nanoblogger, rawdog
		# - copia ciboulette
		# - actualizar ciboulette

		# ---------------------  DEPENDENCIAS -----------------------------


		echo
		echo "Instalando dependencias"
		echo "-----------------------"
		echo

		# verifica el sistema operativo
		if [ "$(which yum)" ]; then
			aptitude="yum -y install"
		elif [ "$(which pacman)" ]; then
			aptitude="yaourt -S"
		else
			aptitude="apt-get -y install"
		fi
		if [ "$(which gksu)" ]; then
			gksu="gksu"
		else
			gksu="su -c"
		fi

		echo "" > $TMP
	        if [ "$(uname -r | grep ARCH)" ]; then
			# en Arch
			echo "darkhttpd tor torsocks zenity nanoblogger rawdog python2-feedparser" | \
			sed 's/\ /\n/g' | while read i; do
				[ ! "$(which $i)" ] && echo "Instalar los programas $i"
			done
		else
			# en Mint, Debian, Fedora (?)
			echo "mini-httpd tor torsocks zenity nanoblogger rawdog libnotify-bin" | \
			sed 's/\ /\n/g' | while read i; do
				[ ! "$(which $i)" ] && echo "$aptitude $i"
			done > $TMP
	        fi

		# ----------------------------- TOR ----------------------------------

		echo
		echo "Configuración de TOR y lanzadores"
		echo "---------------------------------"
		echo

		# Configuración en tor y reinicio del demonio

		echo "echo 'HiddenServiceDir /var/lib/tor/${NOMBRE}/' >> /etc/tor/torrc
		echo 'HiddenServicePort 80 127.0.0.1:4232' >> /etc/tor/torrc
		cp $NOMBRE /usr/local/bin/
		systemctl restart tor 2> /dev/null
		/etc/init.d/tor restart 2> /dev/null
		cp $NOMBRE.png /usr/share/pixmaps/
		cp $NOMBRE.desktop /usr/share/applications/
		sleep 10
		cat "/var/lib/tor/${NOMBRE}/hostname" > /tmp/hostname" >> $TMP

	        echo "Se necesita autenticación como superusuario para instalar los paquetes. Debe proporcionar la contraseña de root"
		$gksu "bash $TMP"
		rm $TMP

		# ----------------------------- INSTALACION ----------------------------------

		echo
		echo "Instalando archivos de $NOMBRE"
		echo "------------------------------"
		echo

                [ -f "$NOVEDADES/config" ] && FEED="$(cat $NOVEDADES/config | grep "^feed ")"

		# Crea el directorio local y temas
		mkdir -p $CARPETA
		cp -r base/* "$CARPETA"

		if [ "$XDG_PUBLICSHARE_DIR" ]; then
			ls -s "$XDG_PUBLICSHARE_DIR" "$COMPARTIR"
			echo "Compartiendo la carpeta $XDG_PUBLICSHARE_DIR"
		else
			# crea la carpeta compartir si esta no se puede asociar a la del sistema
			mkdir $COMPARTIR &> /dev/null
		fi

		echo "$FEED" >> "$NOVEDADES/config"

		# direccion de tu ciboulette
		echo "http://$(cat /tmp/hostname)" > ${CARPETA}hostname

		mkdir ~/.config/autostart/ &> /dev/null
		cp $NOMBRE.desktop  ~/.config/autostart/

		[ -d "${CARPETA}data" ] && sh chronicle2nanoblogger

		# instala el blog en el directorio
		# nb -b "$BLOG" --template-dir "$BLOG/templates" add weblog

		# inicia el servidor
		$NOMBRE -s &
		$NOMBRE -w
		$NOMBRE -d
		(crontab -l | grep -v "# Ciboulette"; echo '*/5  * * * * /usr/local/bin/ciboulette -d &>/dev/null # Ciboulette';) | crontab -
		$NOMBRE -h

		exit
		;;
	esac
done



# -------------------------- Wizard ----------------------------------

# ¿Que queres hacer?
MENU=`echo  "Publicar_un_articulo Cambiar_tu_avatar Editar_perfil Leer_novedades Agrega_nodo_amigo Iniciar_Ciboulette Matar_Ciboulette" | opciones -t "Ciboulette" -m "Ciboulette - $(cat ${CARPETA}hostname)"`
case $MENU in
		0 )
			# Publicar articulo
			TITULO="$(titulo)"
			mensaje | ciboulette -a "$TITULO"
			xdg-open "http://localhost:4232"
		;;
		1 )
			# Imagen del perfil
			ARCHIVO=$(archivo "Imagen del perfil")
			convert "$ARCHIVO" -resize 16x16 ${CARPETA}favicon.ico
			convert "$ARCHIVO" -resize 128x128 ${CARPETA}avatar.png
			qrencode "`cat {$CARPETA}hostname`" -o qr.png
		;;
		2)
			# Configuración del perfil
			xdg-open ${CARPETA}config
		;;
		3)
			# Novedades
			xdg-open "http://localhost:4232/novedades/"
		;;
		4)
			# Agregar nodo
			URL=$(url)
			$NOMBRE -n "$URL"
		;;
		5)
			# Inicia al servidor
			$NOMBRE -s
		;;
		6)
			# Mata el servidor
			$NOMBRE -k
		;;
esac


exit

		# mkdir ~/Ciboulette
		# cd ~/Ciboulette
		# ln -s "$BLOG/data" Blog
		# ln -s "$COMPARTIR" Compartir
		# ln -s "$NOVEDADES" Novedades
		# Deberia crear un acceso a las paginas internas y/o link a los  ejecutables


