#!/bin/bash
#
#	Tu cuenta de chat si usar tor como proxy transparente
#

sudo aptitude install prosody

HOST=$(cat ~/.ciboulette/hostname | sed 's/^.*\/\///g')

# esto va como sudo
cd /etc/prosody/conf.avail

# Todavia no se como hacer para separar las versiones
echo "Host "$HOST"" > "$HOST.cfg.lua"
echo "VirtualHost "$HOST"" >> "$HOST.cfg.lua"

cd ../conf.d
ln -s ../conf.avail/$HOST.cfg.lua .

# reiniciar prosody

sudo /etc/init.d/prosody restart

# -------------------- crea cuenta de XMPP --------------------------

# Instalacion de prosody para chatear con ciboulette
XMPP="${USER}@${HOST}"

CLAVE=$(clave "Clave para el chat")

echo "$CLAVE
$CLAVE
" | sudo prosodyctl adduser $XMPP $CLAVE 2> /dev/null
