#!/bin/bash
#
# Actualizar tor a la ultima version o instalarlo
# AGPLv3

VERSION=$(tor --version | sed 's/(.*$//g; s/[^0-9]//g; s/^0//g; s/\(..\).*/\1/g')

if [ "$(which apt-get)" ] && [ "$VERSION" -lt "24" ]; then
	sh /etc/lsb-release

	echo "tu version de tor es muy vieja... actualizando"
	# comprobar que es un debian
	apt-get purge tor

	echo "deb http://deb.torproject.org/torproject.org $DISTRIB_CODENAME main" >> /etc/apt/source.list

	gpg --keyserver keys.gnupg.net --recv 886DDD89
	gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
	apt-get update
	apt-get install deb.torproject.org-keyring
	apt-get install -y tor
fi

# agrega el soporte para DNS de Tor

echo "DNSPort 127.0.0.1:5300
VirtualAddrNetworkIPv4 10.192.0.0/11
AutomapHostsOnResolve 1
TransPort 9040" >> /etc/tor/torrc

# redirecciona los DNS a Tor

echo " cat /etc/rc.local | grep -v "^exit"
/usr/local/bin/ciboulette iptables
exit 0
" >> /etc/rc.local

# Quehaceres
#
# - solucionar que si tor no esta activado no hay DNS :P
